-- MySQL Script generated by MySQL Workbench
-- 01/23/16 12:18:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema polo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema polo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `polo` DEFAULT CHARACTER SET latin1 ;
USE `polo` ;

-- -----------------------------------------------------
-- Table `polo`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polo`.`admins` ;

CREATE TABLE IF NOT EXISTS `polo`.`admins` (
  `id_admin` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `identifiant` VARCHAR(15) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `reg_date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_admin`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `polo`.`score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polo`.`score` ;

CREATE TABLE IF NOT EXISTS `polo`.`score` (
  `id_score` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `score_jour` INT(10) NOT NULL DEFAULT 0,
  `best_score` INT(10) NOT NULL DEFAULT 0,
  `jetons` INT(5) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_score`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `polo`.`personnage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polo`.`personnage` ;

CREATE TABLE IF NOT EXISTS `polo`.`personnage` (
  `id_personnage` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `espece` VARCHAR(45) NOT NULL DEFAULT 'defaut',
  `couleur` VARCHAR(45) NOT NULL DEFAULT 'defaut',
  PRIMARY KEY (`id_personnage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `polo`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polo`.`logs` ;

CREATE TABLE IF NOT EXISTS `polo`.`logs` (
  `id_log` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `last_log_date` DATE NOT NULL,
  `last_log_time` TIME NOT NULL,
  `nb_log` INT NOT NULL,
  `last_delog_time` DATE NULL,
  `connexion_duration` INT NULL DEFAULT 0,
  PRIMARY KEY (`id_log`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `polo`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polo`.`users` ;

CREATE TABLE IF NOT EXISTS `polo`.`users` (
  `id_user` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(30) NOT NULL,
  `prenom` VARCHAR(30) NOT NULL,
  `matricule` VARCHAR(15) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `question_s_1` MEDIUMTEXT NOT NULL,
  `rep_s_1` VARCHAR(45) NOT NULL,
  `question_s_2` MEDIUMTEXT NOT NULL,
  `rep_s_2` VARCHAR(45) NOT NULL,
  `reg_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `pseudonyme` VARCHAR(45) NOT NULL DEFAULT 'defaut',
  `score_id_score` INT UNSIGNED NOT NULL,
  `personnage_id_personnage` INT UNSIGNED NOT NULL,
  `logs_id_log` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user`, `score_id_score`, `personnage_id_personnage`, `logs_id_log`),
  CONSTRAINT `fk_users_score1`
    FOREIGN KEY (`score_id_score`)
    REFERENCES `polo`.`score` (`id_score`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_personnage1`
    FOREIGN KEY (`personnage_id_personnage`)
    REFERENCES `polo`.`personnage` (`id_personnage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_logs1`
    FOREIGN KEY (`logs_id_log`)
    REFERENCES `polo`.`logs` (`id_log`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_users_score1_idx` ON `polo`.`users` (`score_id_score` ASC);

CREATE INDEX `fk_users_personnage1_idx` ON `polo`.`users` (`personnage_id_personnage` ASC);

CREATE INDEX `fk_users_logs1_idx` ON `polo`.`users` (`logs_id_log` ASC);


-- -----------------------------------------------------
-- Table `polo`.`badges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polo`.`badges` ;

CREATE TABLE IF NOT EXISTS `polo`.`badges` (
  `id_badge` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id_badge`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `polo`.`users_badges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polo`.`users_badges` ;

CREATE TABLE IF NOT EXISTS `polo`.`users_badges` (
  `users_id_user` INT(6) UNSIGNED NOT NULL,
  `badges_id_badge` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`users_id_user`, `badges_id_badge`),
  CONSTRAINT `fk_users_has_badges_users`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `polo`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_badges_badges1`
    FOREIGN KEY (`badges_id_badge`)
    REFERENCES `polo`.`badges` (`id_badge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_users_has_badges_badges1_idx` ON `polo`.`users_badges` (`badges_id_badge` ASC);

CREATE INDEX `fk_users_has_badges_users_idx` ON `polo`.`users_badges` (`users_id_user` ASC);


-- -----------------------------------------------------
-- Table `polo`.`users_quizz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polo`.`users_quizz` ;

CREATE TABLE IF NOT EXISTS `polo`.`users_quizz` (
  `users_id_user` INT(6) UNSIGNED NOT NULL,
  `id_quizz` INT NOT NULL,
  `valide` TINYINT(1) NOT NULL DEFAULT 0,
  `occurence` INT(6) NOT NULL DEFAULT 0,
  PRIMARY KEY (`users_id_user`),
  CONSTRAINT `fk_users_has_quizz_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `polo`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_users_has_quizz_users1_idx` ON `polo`.`users_quizz` (`users_id_user` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `polo`.`personnage`
-- -----------------------------------------------------
START TRANSACTION;
USE `polo`;
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (1, 'Qi', 'Green');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (2, 'Qi', 'Red');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (3, 'Qi', 'Yellow');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (4, 'Qi', 'Beige');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (5, 'Qi', 'Purple');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (6, 'Qi', 'Blue');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (7, 'Tec', 'Green');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (8, 'Tec', 'Red');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (9, 'Tec', 'Yellow');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (10, 'Tec', 'Beige');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (11, 'Tec', 'Purple');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (12, 'Tec', 'Blue');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (13, 'Pri', 'Green');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (14, 'Pri', 'Red');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (15, 'Pri', 'Yellow');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (16, 'Pri', 'Beige');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (17, 'Pri', 'Purple');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (18, 'Pri', 'Blue');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (19, 'Lav', 'Green');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (20, 'Lav', 'Red');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (21, 'Lav', 'Yellow');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (22, 'Lav', 'Beige');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (23, 'Lav', 'Purple');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (24, 'Lav', 'Blue');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (25, 'Tut', 'Green');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (26, 'Tut', 'Red');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (27, 'Tut', 'Yellow');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (28, 'Tut', 'Beige');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (29, 'Tut', 'Purple');
INSERT INTO `polo`.`personnage` (`id_personnage`, `espece`, `couleur`) VALUES (30, 'Tut', 'Blue');

COMMIT;


-- -----------------------------------------------------
-- Data for table `polo`.`badges`
-- -----------------------------------------------------
START TRANSACTION;
USE `polo`;
INSERT INTO `polo`.`badges` (`id_badge`, `nom`, `description`) VALUES (1, 'C\'est parti !', 'Avoir créé son personnage');
INSERT INTO `polo`.`badges` (`id_badge`, `nom`, `description`) VALUES (2, '1k', 'Avoir 1000 points de score');
INSERT INTO `polo`.`badges` (`id_badge`, `nom`, `description`) VALUES (3, 'Let\'s play.', 'Jouer à un mini-jeux');

COMMIT;

